# 베이스 이미지 설정
FROM eclipse-temurin:21

# 작업 디렉토리 설정
WORKDIR /app

# Gradle Wrapper, 빌드 스크립트, 그리고 애플리케이션 소스 코드 복사
COPY ./ /app

# 애플리케이션 빌드와 JAR 파일 생성
RUN ./gradlew build

# 빌드된 실행 가능한 JAR 파일을 실행
ENTRYPOINT ["java", "-jar", "build/libs/demo-dockerfile-cache-0.0.1-SNAPSHOT.jar"]
