FROM eclipse-temurin:21

WORKDIR /app

# gradle 관련 파일 복사
COPY gradlew /app/
COPY gradle /app/gradle
COPY build.gradle /app/
COPY settings.gradle /app/

RUN ./gradlew dependencies

# 소스 코드 복사
COPY src /app/src


RUN ./gradlew --info build

ENTRYPOINT ["java", "-jar", "build/libs/demo-dockerfile-cache-0.0.1-SNAPSHOT.jar"]
